CREATE TABLE IF NOT EXISTS "personal" (
	-- llave primaria e identificador de cada registro
	"id_per" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- cedula del empleado 
	"ced_per" VARCHAR(15) NOT NULL UNIQUE,
	-- nombre y apellido del empleado
	"nom_per" VARCHAR(50) NOT NULL,
	-- llave foranea que relaciona el empleado con su cargo y gremio al que pertenece
	"fky_grem" INTEGER NOT NULL,
	-- estado del empleado 
	-- i = inactivo
	-- a = activo
	"est_per" VARCHAR(1) NOT NULL,
	PRIMARY KEY("id_per")
);

COMMENT ON TABLE "personal" IS 'tabla para almacenar los datos de los empleados de la universidad ';
COMMENT ON COLUMN "personal"."id_per" IS 'llave primaria e identificador de cada registro';
COMMENT ON COLUMN "personal"."ced_per" IS 'cedula del empleado ';
COMMENT ON COLUMN "personal"."nom_per" IS 'nombre y apellido del empleado';
COMMENT ON COLUMN "personal"."fky_grem" IS 'llave foranea que relaciona el empleado con su cargo y gremio al que pertenece';
COMMENT ON COLUMN "personal"."est_per" IS 'estado del empleado 
i = inactivo
a = activo';


CREATE TABLE IF NOT EXISTS "gremio" (
	-- llave primaria e identificador de cada registro
	"id_grem" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- nombre del gremio al que pertenece: Docente, Obrero o Administrativo
	"nom_grem" VARCHAR(50) NOT NULL,
	-- cargo al que pertenece dentro del gremio, personal obrero(Obrero), docente(Docente), analista rrhh( Administrativo)... 
	"carg_grem" VARCHAR(255) NOT NULL,
	-- estado del registro: i= inactivo, a = activo
	"est_grem" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_grem")
);

COMMENT ON TABLE "gremio" IS 'tabla para gestionar los cargos a los que pertenece cada empleado';
COMMENT ON COLUMN "gremio"."id_grem" IS 'llave primaria e identificador de cada registro';
COMMENT ON COLUMN "gremio"."nom_grem" IS 'nombre del gremio al que pertenece: Docente, Obrero o Administrativo';
COMMENT ON COLUMN "gremio"."carg_grem" IS 'cargo al que pertenece dentro del gremio, personal obrero(Obrero), docente(Docente), analista rrhh( Administrativo)... ';
COMMENT ON COLUMN "gremio"."est_grem" IS 'estado del registro: i= inactivo, a = activo';


CREATE TABLE IF NOT EXISTS "usuario" (
	-- llave primaria e identificador único de cada registro
	"id_usu" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- nombre de usuario para acceder al sistema
	"nom_usu" VARCHAR(50) NOT NULL,
	-- clave para de usuario para acceder al sistema
	"cla_usu" VARCHAR(255) NOT NULL,
	-- llave foranera a la tabla rol para tener el control de acceso por roles de usuario
	"fky_rol" INTEGER NOT NULL,
	-- llave foranea que hace referencia a la tabla persona para tener los datos del empleado que accede al sistema
	"fky_per" INTEGER NOT NULL,
	-- estado del usuario i = inactivo
	-- a = activo
	"est_usu" VARCHAR(1) NOT NULL,
	PRIMARY KEY("id_usu")
);

COMMENT ON TABLE "usuario" IS 'tabla para gestionar los datos del usuario ';
COMMENT ON COLUMN "usuario"."id_usu" IS 'llave primaria e identificador único de cada registro';
COMMENT ON COLUMN "usuario"."nom_usu" IS 'nombre de usuario para acceder al sistema';
COMMENT ON COLUMN "usuario"."cla_usu" IS 'clave para de usuario para acceder al sistema';
COMMENT ON COLUMN "usuario"."fky_rol" IS 'llave foranera a la tabla rol para tener el control de acceso por roles de usuario';
COMMENT ON COLUMN "usuario"."fky_per" IS 'llave foranea que hace referencia a la tabla persona para tener los datos del empleado que accede al sistema';
COMMENT ON COLUMN "usuario"."est_usu" IS 'estado del usuario i = inactivo
a = activo';


CREATE TABLE IF NOT EXISTS "rol" (
	-- llave primaria e identificador unico de cada registro
	"id_rol" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- nombre del rol que van desde 
	-- admin: quien tiene control total sobre el sistema.
	-- vigilante: quien se encargar de registrar la salida y le entrada de los empleados.
	-- jefeRRHH: quien podra podra acceder para gestionar las asistencias y generar reportes
	"nom_rol" VARCHAR(255) NOT NULL,
	-- estado del registro i=inactivo, a=activo
	"est_rol" VARCHAR(1) NOT NULL,
	PRIMARY KEY("id_rol")
);

COMMENT ON TABLE "rol" IS 'tabla para gestionar los roles de los usuarios';
COMMENT ON COLUMN "rol"."id_rol" IS 'llave primaria e identificador unico de cada registro';
COMMENT ON COLUMN "rol"."nom_rol" IS 'nombre del rol que van desde 
admin: quien tiene control total sobre el sistema.
vigilante: quien se encargar de registrar la salida y le entrada de los empleados.
jefeRRHH: quien podra podra acceder para gestionar las asistencias y generar reportes';
COMMENT ON COLUMN "rol"."est_rol" IS 'estado del registro i=inactivo, a=activo';


CREATE TABLE IF NOT EXISTS "turno_mañana" (
	"id_turn_man" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- registrara la fecha de la asistencia en el turno de la mañana
	"fec_asi_tm" DATE NOT NULL,
	-- llave foranea que hace referencia a la tabla persona
	"fky_per" INTEGER NOT NULL,
	-- campo para registrar la hora de llegada
	"tm_hor_lleg" TIMESTAMP,
	-- campo para registrar la hora de salida
	"tm_hor_sal" TIMESTAMP,
	-- campo para registrar las horas de trabajo que tuvo el empleado en el turno de la mañana
	"hor_tra_tm" DECIMAL(5,2),
	-- estado del registro i=inactivo,     a=activo
	"est_tm" VARCHAR(1) NOT NULL,
	PRIMARY KEY("id_turn_man")
);

COMMENT ON TABLE "turno_mañana" IS 'tabla para gestionar las asistencias del personal en el turno de la mañana';
COMMENT ON COLUMN "turno_mañana"."fec_asi_tm" IS 'registrara la fecha de la asistencia en el turno de la mañana';
COMMENT ON COLUMN "turno_mañana"."fky_per" IS 'llave foranea que hace referencia a la tabla persona';
COMMENT ON COLUMN "turno_mañana"."tm_hor_lleg" IS 'campo para registrar la hora de llegada';
COMMENT ON COLUMN "turno_mañana"."tm_hor_sal" IS 'campo para registrar la hora de salida';
COMMENT ON COLUMN "turno_mañana"."hor_tra_tm" IS 'campo para registrar las horas de trabajo que tuvo el empleado en el turno de la mañana';
COMMENT ON COLUMN "turno_mañana"."est_tm" IS 'estado del registro i=inactivo,     a=activo';


CREATE TABLE IF NOT EXISTS "turno_tarde" (
	-- llave primaria e identificador unico de cada registro
	"id_turn_tar" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- campo para registrar la fecha de la asistencia en el turno de la tarde
	"fec_asi_tt" DATE,
	-- llave foranea que hace referencia a la tabla persona
	"fky_per" INTEGER,
	-- campo para registrar la hora llegada en el turno de la tarde
	"tt_hor_lleg" TIMESTAMP NOT NULL,
	-- campo para registrar la hora de salida en el turno de la tarde
	"tt_hor_sal" TIMESTAMP NOT NULL,
	-- campo para registrar las horas trabajo que tuvo el empleado en el turno de la tarde
	-- 
	"hor_tra_tt" DECIMAL(5,2) NOT NULL,
	-- estado del registro i: inactivo, a: activo
	"est_tt" VARCHAR(255),
	PRIMARY KEY("id_turn_tar")
);

COMMENT ON TABLE "turno_tarde" IS 'tabla para gestionar las asistencias del personal en el turno de la tarde';
COMMENT ON COLUMN "turno_tarde"."id_turn_tar" IS 'llave primaria e identificador unico de cada registro';
COMMENT ON COLUMN "turno_tarde"."fec_asi_tt" IS 'campo para registrar la fecha de la asistencia en el turno de la tarde';
COMMENT ON COLUMN "turno_tarde"."fky_per" IS 'llave foranea que hace referencia a la tabla persona';
COMMENT ON COLUMN "turno_tarde"."tt_hor_lleg" IS 'campo para registrar la hora llegada en el turno de la tarde';
COMMENT ON COLUMN "turno_tarde"."tt_hor_sal" IS 'campo para registrar la hora de salida en el turno de la tarde';
COMMENT ON COLUMN "turno_tarde"."hor_tra_tt" IS 'campo para registrar las horas trabajo que tuvo el empleado en el turno de la tarde
';
COMMENT ON COLUMN "turno_tarde"."est_tt" IS 'estado del registro i: inactivo, a: activo';

ALTER TABLE "personal"
ADD FOREIGN KEY("fky_grem") REFERENCES "gremio"("id_grem")
ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "turno_tarde"
ADD FOREIGN KEY("fky_per") REFERENCES "personal"("id_per")
ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "turno_mañana"
ADD FOREIGN KEY("fky_per") REFERENCES "personal"("id_per")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "usuario"
ADD FOREIGN KEY("fky_rol") REFERENCES "rol"("id_rol")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "usuario"
ADD FOREIGN KEY("fky_per") REFERENCES "personal"("id_per")
ON UPDATE NO ACTION ON DELETE NO ACTION;